- hosts: all
  become: yes
  tasks:
    - name: Download ruby-install
      become: no
      get_url:
        url: https://github.com/postmodern/ruby-install/archive/v0.8.3.tar.gz
        dest: /home/ubuntu/ruby-install-0.8.3.tar.gz
    - name: Extract ruby install tarball                                                                                                                                                
      become: no
      unarchive:
        src: /home/ubuntu/ruby-install-0.8.3.tar.gz
        dest: /home/ubuntu
        creates: /home/ubuntu/ruby-install-0.8.3
        remote_src: yes
    - name: Install ruby-install
      make:
        chdir: /home/ubuntu/ruby-install-0.8.3
        target: install
    - name: Install Ruby
      become_user: deploy
      command: /usr/local/bin/ruby-install --no-install-deps ruby 3.1.0
      args:
        creates: /home/deploy/.rubies/ruby-3.1.0
    - name: Download chruby
      become: no
      get_url:
        url: https://github.com/postmodern/chruby/archive/v0.3.9.tar.gz
        dest: /home/ubuntu/chruby-0.3.9.tar.gz
    - name: Extract chruby tarball
      become: no
      unarchive:
        src: /home/ubuntu/chruby-0.3.9.tar.gz
        dest: /home/ubuntu
        creates: /home/ubuntu/chruby-0.3.9
        remote_src: yes
    - name: Install chruby
      make:
        chdir: /home/ubuntu/chruby-0.3.9
        target: install
    - name: Load chruby for deploy user
      lineinfile:
        path: /home/deploy/.bashrc
        regexp: 'chruby.sh$'
        line: 'source /usr/local/share/chruby/chruby.sh'
        insertbefore: BOF
    - name: Set ruby version for deploy user
      lineinfile:
        path: /home/deploy/.profile
        regexp: '^chruby'
        line: 'chruby ruby-3.1.0'
    - name: Install bundler
      become_user: deploy
      command: 'chruby-exec ruby-3.1.0 -- gem install bundler'
      args:
        creates: /home/deploy/.gem/ruby/3.1.0/bin/bundle
