- hosts: all
  become: yes
  tasks:
    - name: Install Ruby dependencies
      apt:
        name: "{{ item }}"
      with_items:
        - gcc
        - autoconf
        - bison
        - build-essential
        - libssl-dev
        - libyaml-dev
        - libreadline6-dev
        - zlib1g-dev
        - libncurses5-dev
        - libffi-dev
        - nodejs
        - wget
        - python3-psycopg2
        - acl
        - postgresql
        - libpq-dev
      notify:
        - Enable Postgresql

  handlers:
      - import_tasks: ../shared/handlers/main.yml
